import { Metadata } from "next";
import { HomePageWrapper } from "./components";

export const metadata: Metadata = {
  title: "Unsplash Image",
  description: "Generated by create next app"
};
export default function Home() {
  return <HomePageWrapper />;
}
